---
title: "First_Quarto_File"
---

## Websites Found

### [The Pudding](https://pudding.cool/)
It explores the world of Spotify with easy access to the information while forming the connection with the social opinions. Whilst written in neutral aspect, it visualizes the data in such a manner that each piece of information creates a battle in your brain with completely opposite perspectives. Simply, it illustrates the data in such a manner that every piece of information is compelling and provocative.

Despite being thought provoking, the actual visualization of data is minimal and often represented in words rather than graphs making it slightly boring after a while.



### [The Fortune 500 CEO With The Best and Worst](https://priceonomics.com/the-fortune-500-ceos-with-the-best-and-worst/)

It is simple, to the point and funny. It doesn't have many comparison at the same time making it easy to understand. It also tries to establish relationship between two different aspects which seem totally unrelated. While using some scientific factors to draw the conclusion, it also doesn't let the viewer to get lost in completely irrelevant information. 

However, the prospect of the article is too short and the comparisons too less. Even when passing the most important information, it fails to convince the viewers on the data it is trying pass.



### [FiveThirtyEight](https://fivethirtyeight.com/)

It has graphical illustrations of approval ratings and other political opinions for elections. Most of the data are represented in the form of scattered plot. A little bit harder to navigate, it still provides vital information on current political situation of the country. It however has much visualizations for one single political party and seems to provide information on highly biased manner.

Navigation is worst and graphs are not interactive at all. It is hard to establish a little less obvious information as the labeling isn't done in clear manner.
```{r}
plot(1:20);
```
